# Generated by Django 3.0.6 on 2020-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_extra_for_sub_order_order_to_food_topping'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order_to_food',
            constraint=models.CheckConstraint(check=models.Q(quantity__gt=0), name='quantity_gt_0'),
        ),
    ]
